using Joby.Application.DTOs.Applications;
using Joby.Application.DTOs.Reminders;
using Joby.Application.Interfaces;
using Joby.Domain.Entities;
using Joby.Domain.Enums;
using Joby.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace Joby.Infrastructure.Services;

public class ReminderService : IReminderService
{
    private readonly ApplicationDbContext _context;

    public ReminderService(ApplicationDbContext context)
    {
        _context = context;
    }

    public async Task<ReminderDto> CreateReminderAsync(Guid userId, CreateReminderRequest request)
    {
        // Verify application belongs to user if specified
        if (request.ApplicationId.HasValue)
        {
            var application = await _context.Applications
                .FirstOrDefaultAsync(a => a.Id == request.ApplicationId && a.UserId == userId);

            if (application == null)
            {
                throw new KeyNotFoundException("Application not found");
            }
        }

        var reminder = new Reminder
        {
            UserId = userId,
            ApplicationId = request.ApplicationId,
            Title = request.Title,
            Description = request.Description,
            DueAt = request.DueAt,
            ReminderType = request.ReminderType ?? "Custom",
            IsAutoGenerated = false
        };

        _context.Reminders.Add(reminder);
        await _context.SaveChangesAsync();

        return MapToDto(reminder);
    }

    public async Task<List<ReminderDto>> GetRemindersAsync(Guid userId, bool includePast = false)
    {
        var query = _context.Reminders
            .Where(r => r.UserId == userId);

        if (!includePast)
        {
            query = query.Where(r =>
                r.Status == ReminderStatus.Pending ||
                r.Status == ReminderStatus.Snoozed);
        }

        var reminders = await query
            .OrderBy(r => r.DueAt)
            .ToListAsync();

        return reminders.Select(MapToDto).ToList();
    }

    public async Task<List<ReminderDto>> GetUpcomingRemindersAsync(Guid userId, int days = 7)
    {
        var endDate = DateTime.UtcNow.AddDays(days);

        var reminders = await _context.Reminders
            .Where(r => r.UserId == userId &&
                       (r.Status == ReminderStatus.Pending || r.Status == ReminderStatus.Snoozed) &&
                       r.DueAt <= endDate)
            .OrderBy(r => r.DueAt)
            .ToListAsync();

        return reminders.Select(MapToDto).ToList();
    }

    public async Task<ReminderDto> SnoozeReminderAsync(Guid userId, Guid reminderId, SnoozeReminderRequest request)
    {
        var reminder = await _context.Reminders
            .FirstOrDefaultAsync(r => r.Id == reminderId && r.UserId == userId);

        if (reminder == null)
        {
            throw new KeyNotFoundException("Reminder not found");
        }

        reminder.Status = ReminderStatus.Snoozed;
        reminder.SnoozedUntil = request.SnoozedUntil;
        reminder.DueAt = request.SnoozedUntil;

        await _context.SaveChangesAsync();

        return MapToDto(reminder);
    }

    public async Task<ReminderDto> CompleteReminderAsync(Guid userId, Guid reminderId)
    {
        var reminder = await _context.Reminders
            .FirstOrDefaultAsync(r => r.Id == reminderId && r.UserId == userId);

        if (reminder == null)
        {
            throw new KeyNotFoundException("Reminder not found");
        }

        reminder.Status = ReminderStatus.Completed;
        reminder.CompletedAt = DateTime.UtcNow;

        await _context.SaveChangesAsync();

        return MapToDto(reminder);
    }

    public async Task<ReminderDto> DismissReminderAsync(Guid userId, Guid reminderId)
    {
        var reminder = await _context.Reminders
            .FirstOrDefaultAsync(r => r.Id == reminderId && r.UserId == userId);

        if (reminder == null)
        {
            throw new KeyNotFoundException("Reminder not found");
        }

        reminder.Status = ReminderStatus.Dismissed;

        await _context.SaveChangesAsync();

        return MapToDto(reminder);
    }

    public async Task CreateFollowUpReminderAsync(Guid userId, Guid applicationId, int daysAfterApplied)
    {
        // Check if there's already a follow-up reminder for this application
        var existingReminder = await _context.Reminders
            .FirstOrDefaultAsync(r =>
                r.ApplicationId == applicationId &&
                r.ReminderType == "FollowUp" &&
                r.Status == ReminderStatus.Pending);

        if (existingReminder != null)
        {
            return; // Don't create duplicate
        }

        var application = await _context.Applications
            .Include(a => a.Job)
            .FirstOrDefaultAsync(a => a.Id == applicationId);

        if (application == null)
        {
            return;
        }

        var reminder = new Reminder
        {
            UserId = userId,
            ApplicationId = applicationId,
            Title = $"Follow up on {application.Job.Title} at {application.Job.Company}",
            Description = "It's been a while since you applied. Consider sending a follow-up email.",
            DueAt = DateTime.UtcNow.AddDays(daysAfterApplied),
            ReminderType = "FollowUp",
            IsAutoGenerated = true
        };

        _context.Reminders.Add(reminder);
        await _context.SaveChangesAsync();
    }

    private static ReminderDto MapToDto(Reminder reminder) => new()
    {
        Id = reminder.Id,
        ApplicationId = reminder.ApplicationId,
        Title = reminder.Title,
        Description = reminder.Description,
        DueAt = reminder.DueAt,
        Status = reminder.Status,
        CompletedAt = reminder.CompletedAt,
        SnoozedUntil = reminder.SnoozedUntil,
        IsAutoGenerated = reminder.IsAutoGenerated,
        ReminderType = reminder.ReminderType,
        CreatedAt = reminder.CreatedAt
    };
}





