using Joby.Application.DTOs.Jobs;
using Joby.Domain.Enums;

namespace Joby.Application.DTOs.Applications;

public class ApplicationDto
{
    public Guid Id { get; set; }
    public Guid JobId { get; set; }
    public JobDto Job { get; set; } = null!;
    public ApplicationStatus Status { get; set; }
    public string StatusDisplay => Status.ToString();
    public DateTime? AppliedAt { get; set; }
    public string? Notes { get; set; }
    public string? ContactName { get; set; }
    public string? ContactEmail { get; set; }
    public string? ContactPhone { get; set; }
    public Guid? ResumeId { get; set; }
    public List<ApplicationEventDto> Events { get; set; } = new();
    public List<ReminderDto> Reminders { get; set; } = new();
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}

public class ApplicationEventDto
{
    public Guid Id { get; set; }
    public string EventType { get; set; } = string.Empty;
    public string? Description { get; set; }
    public ApplicationStatus? OldStatus { get; set; }
    public ApplicationStatus? NewStatus { get; set; }
    public DateTime? ScheduledAt { get; set; }
    public DateTime CreatedAt { get; set; }
}

public class ReminderDto
{
    public Guid Id { get; set; }
    public Guid? ApplicationId { get; set; }
    public Guid? JobId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public DateTime DueAt { get; set; }
    public ReminderStatus Status { get; set; }
    public string StatusDisplay => Status.ToString();
    public DateTime? CompletedAt { get; set; }
    public DateTime? SnoozedUntil { get; set; }
    public bool IsAutoGenerated { get; set; }
    public string? ReminderType { get; set; }
    public DateTime? EmailSentAt { get; set; }
    public DateTime CreatedAt { get; set; }
}





