using Joby.Domain.Enums;

namespace Joby.Domain.Entities;

public class Reminder : BaseEntity
{
    public Guid UserId { get; set; }
    public Guid? ApplicationId { get; set; }
    
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public DateTime DueAt { get; set; }
    
    public ReminderStatus Status { get; set; } = ReminderStatus.Pending;
    public DateTime? CompletedAt { get; set; }
    public DateTime? SnoozedUntil { get; set; }
    
    // Whether this was auto-generated (e.g., follow-up reminder)
    public bool IsAutoGenerated { get; set; }
    public string? ReminderType { get; set; } // FollowUp, Interview, Custom
    
    // Navigation
    public User User { get; set; } = null!;
    public Application? Application { get; set; }
}





