using Joby.Application.DTOs.Reminders;
using Joby.Domain.Entities;
using Joby.Domain.Enums;
using Joby.Infrastructure.Persistence;
using Joby.Infrastructure.Services;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace Joby.Tests;

public class ReminderServiceTests
{
    private readonly ApplicationDbContext _context;
    private readonly ReminderService _service;

    public ReminderServiceTests()
    {
        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseInMemoryDatabase(databaseName: Guid.NewGuid().ToString())
            .Options;

        _context = new ApplicationDbContext(options);
        _service = new ReminderService(_context);
    }

    [Fact]
    public async Task CreateReminder_WithValidData_CreatesReminder()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var user = new User
        {
            Id = userId,
            Email = "test@example.com",
            PasswordHash = "hash",
            FirstName = "Test",
            LastName = "User"
        };

        _context.Users.Add(user);
        await _context.SaveChangesAsync();

        var request = new CreateReminderRequest
        {
            Title = "Follow up with HR",
            Description = "Send a thank you email",
            DueAt = DateTime.UtcNow.AddDays(3),
            ReminderType = "Custom"
        };

        // Act
        var result = await _service.CreateReminderAsync(userId, request);

        // Assert
        Assert.NotNull(result);
        Assert.Equal(request.Title, result.Title);
        Assert.Equal(request.Description, result.Description);
        Assert.Equal(ReminderStatus.Pending, result.Status);
        Assert.False(result.IsAutoGenerated);
    }

    [Fact]
    public async Task CreateFollowUpReminder_AfterApplication_CreatesAutoGeneratedReminder()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var user = new User
        {
            Id = userId,
            Email = "test2@example.com",
            PasswordHash = "hash",
            FirstName = "Test",
            LastName = "User"
        };

        var job = new Job
        {
            UserId = userId,
            Title = "Software Engineer",
            Company = "TechCorp"
        };

        var application = new Domain.Entities.Application
        {
            UserId = userId,
            JobId = job.Id,
            Status = ApplicationStatus.Applied
        };

        _context.Users.Add(user);
        _context.Jobs.Add(job);
        _context.Applications.Add(application);
        await _context.SaveChangesAsync();

        // Act
        await _service.CreateFollowUpReminderAsync(userId, application.Id, 7);

        // Assert
        var reminder = await _context.Reminders
            .FirstOrDefaultAsync(r => r.ApplicationId == application.Id);

        Assert.NotNull(reminder);
        Assert.True(reminder.IsAutoGenerated);
        Assert.Equal("FollowUp", reminder.ReminderType);
        Assert.Contains("Software Engineer", reminder.Title);
        Assert.Contains("TechCorp", reminder.Title);
        Assert.True(reminder.DueAt > DateTime.UtcNow.AddDays(6));
    }

    [Fact]
    public async Task CreateFollowUpReminder_WhenAlreadyExists_DoesNotCreateDuplicate()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var user = new User
        {
            Id = userId,
            Email = "test3@example.com",
            PasswordHash = "hash",
            FirstName = "Test",
            LastName = "User"
        };

        var job = new Job
        {
            UserId = userId,
            Title = "Developer",
            Company = "Company"
        };

        var application = new Domain.Entities.Application
        {
            UserId = userId,
            JobId = job.Id,
            Status = ApplicationStatus.Applied
        };

        _context.Users.Add(user);
        _context.Jobs.Add(job);
        _context.Applications.Add(application);
        await _context.SaveChangesAsync();

        // Create first reminder
        await _service.CreateFollowUpReminderAsync(userId, application.Id, 7);

        // Act - try to create duplicate
        await _service.CreateFollowUpReminderAsync(userId, application.Id, 7);

        // Assert
        var reminders = await _context.Reminders
            .Where(r => r.ApplicationId == application.Id && r.ReminderType == "FollowUp")
            .ToListAsync();

        Assert.Single(reminders);
    }

    [Fact]
    public async Task SnoozeReminder_UpdatesDueDateAndStatus()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var user = new User
        {
            Id = userId,
            Email = "test4@example.com",
            PasswordHash = "hash",
            FirstName = "Test",
            LastName = "User"
        };

        var reminder = new Reminder
        {
            UserId = userId,
            Title = "Test Reminder",
            DueAt = DateTime.UtcNow.AddDays(1),
            Status = ReminderStatus.Pending
        };

        _context.Users.Add(user);
        _context.Reminders.Add(reminder);
        await _context.SaveChangesAsync();

        var newDueDate = DateTime.UtcNow.AddDays(3);
        var request = new SnoozeReminderRequest { SnoozedUntil = newDueDate };

        // Act
        var result = await _service.SnoozeReminderAsync(userId, reminder.Id, request);

        // Assert
        Assert.Equal(ReminderStatus.Snoozed, result.Status);
        Assert.Equal(newDueDate, result.SnoozedUntil);
        Assert.Equal(newDueDate, result.DueAt);
    }

    [Fact]
    public async Task CompleteReminder_UpdatesStatusAndCompletedAt()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var user = new User
        {
            Id = userId,
            Email = "test5@example.com",
            PasswordHash = "hash",
            FirstName = "Test",
            LastName = "User"
        };

        var reminder = new Reminder
        {
            UserId = userId,
            Title = "Test Reminder",
            DueAt = DateTime.UtcNow.AddDays(1),
            Status = ReminderStatus.Pending
        };

        _context.Users.Add(user);
        _context.Reminders.Add(reminder);
        await _context.SaveChangesAsync();

        // Act
        var result = await _service.CompleteReminderAsync(userId, reminder.Id);

        // Assert
        Assert.Equal(ReminderStatus.Completed, result.Status);
        Assert.NotNull(result.CompletedAt);
    }

    [Fact]
    public async Task GetUpcomingReminders_ReturnsOnlyFutureReminders()
    {
        // Arrange
        var userId = Guid.NewGuid();
        var user = new User
        {
            Id = userId,
            Email = "test6@example.com",
            PasswordHash = "hash",
            FirstName = "Test",
            LastName = "User"
        };

        var reminder1 = new Reminder
        {
            UserId = userId,
            Title = "Upcoming",
            DueAt = DateTime.UtcNow.AddDays(2),
            Status = ReminderStatus.Pending
        };

        var reminder2 = new Reminder
        {
            UserId = userId,
            Title = "Far Future",
            DueAt = DateTime.UtcNow.AddDays(10),
            Status = ReminderStatus.Pending
        };

        var reminder3 = new Reminder
        {
            UserId = userId,
            Title = "Completed",
            DueAt = DateTime.UtcNow.AddDays(1),
            Status = ReminderStatus.Completed
        };

        _context.Users.Add(user);
        _context.Reminders.AddRange(reminder1, reminder2, reminder3);
        await _context.SaveChangesAsync();

        // Act
        var result = await _service.GetUpcomingRemindersAsync(userId, 7);

        // Assert
        Assert.Single(result);
        Assert.Equal("Upcoming", result[0].Title);
    }
}




