apiVersion: v1
kind: ConfigMap
metadata:
  name: joby-config
  namespace: joby
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Jwt__Issuer: "Joby"
  Jwt__Audience: "JobyApp"
  Jwt__AccessTokenExpirationMinutes: "60"
  Jwt__RefreshTokenExpirationDays: "7"
  S3_BUCKET_NAME: "REPLACE_WITH_S3_BUCKET_NAME"
  AWS_REGION: "REPLACE_WITH_AWS_REGION"
  Cors__AllowedOrigins__0: "REPLACE_WITH_CORS_ALLOWED_ORIGIN"
  Database__ApplyMigrationsOnStartup: "false"
  Metrics__Enabled: "false"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
