apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: joby
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - clustersecretstore.yaml
  - externalsecret.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
