apiVersion: v1
kind: Secret
metadata:
  name: joby-secrets
  namespace: joby
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=REPLACE_WITH_RDS_HOST;Port=5432;Database=joby;Username=joby_admin;Password=CHANGE_ME"
  Jwt__Secret: "CHANGE_ME_TO_A_SECURE_SECRET_AT_LEAST_32_CHARACTERS_LONG"
